version: '3.9'

name: grocery-app

services:
  traefik:
    image: traefik:2
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=user@localhost"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

  grocery-pos-app:
    build: .
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocery-pos-app.rule=Host(`grocery-app.${DOMAIN_NAME}`)
      - traefik.http.routers.grocery-pos-app.entrypoints=websecure
      - traefik.http.routers.grocery-pos-app.tls.certresolver=myresolver
      - traefik.http.services.grocery-pos-app.loadbalancer.server.port=3000
    depends_on:
      - typesense

  typesense:
    image: typesense/typesense:29.0
    restart: always
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

volumes:
  typesense-data:
  letsencrypt:
